source "https://cdn.cocoapods.org/"

platform :ios, "14.0"
use_frameworks! :linkage => :static

target "Example" do
  pod "Lynx", "4.0.0", :subspecs => ["Framework"]
  pod "PrimJS", "4.0.0", :subspecs => ["quickjs", "napi"]
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "14.0"
      config.build_settings["CLANG_CXX_LANGUAGE_STANDARD"] = "gnu++17"
      config.build_settings["GCC_ENABLE_CPP_EXCEPTIONS"] = "YES"
      config.build_settings["GCC_ENABLE_CPP_RTTI"] = "YES"
      if target.name == "Lynx"
        config.build_settings["CLANG_WARN_DEPRECATED_DECLARATIONS"] = "NO"
        config.build_settings["CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS"] = "NO"
      end
    end
    next unless target.name == "Lynx"

    target.source_build_phase.files.each do |build_file|
      flags = build_file.settings && build_file.settings["COMPILER_FLAGS"]
      next unless flags&.include?("-Werror")

      build_file.settings["COMPILER_FLAGS"] = "#{flags} -Wno-error=deprecated-declarations"
    end
  end
end
